name       : haskell-monadlib
version    : '3.10'
release    : 4
source     :
    - https://hackage.haskell.org/package/monadLib-3.10/monadLib-3.10.tar.gz : 615c4e0f43491950da36608f968fc28d07a9128e7662d5481891a9a40d667ba3
license    : BSD-3-Clause
component  : programming.haskell
summary    : A collection of monad transformers.
description: |
    A collection of monad transformers.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
