name       : haskell-monadlib
version    : 3.7.3
release    : 3
source     :
    - http://hackage.haskell.org/package/monadLib-3.7.3/monadLib-3.7.3.tar.gz : 1834a77560d9df7ab0bc43ce24c77ffc660fc84573730ea94cb6e4ab8dcca99e
license    : BSD-3-Clause
component  : programming.haskell
summary    : A collection of monad transformers.
description: |
    A collection of monad transformers.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
